FROM python:3

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code

RUN apt-get update && apt-get install -y netcat-openbsd

COPY ./game/requirements.txt /code/

RUN pip install --no-cache-dir -r requirements.txt && mkdir -p /etc/ssh

COPY ./game /code/

EXPOSE 3000

CMD [ "daphne" , "-b", "0.0.0.0", "-p", "8000", "game.asgi:application" ]