FROM python:3

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code

RUN apt-get update && apt-get install -y netcat-openbsd

COPY ./ft_back/requirements.txt /code/

RUN pip install --no-cache-dir -r requirements.txt && mkdir -p /etc/ssh

COPY ./ft_back /code/

COPY --chmod=755 ./ft_back/entrypoint.sh /code/

EXPOSE 8000

ENTRYPOINT [ "sh" , "/code/entrypoint.sh" ]

CMD [ "daphne" , "-b", "0.0.0.0", "-p", "8000", "backend.asgi:application" ]
